// <auto-generated />
namespace OnlineAppointment.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class required3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(required3));
        
        string IMigrationMetadata.Id
        {
            get { return "202111231857143_required3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
